title: Lava's Notes
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://lava-chen.github.io/my-notes

aux_links:
  Template Repository: https://github.com/lava-chen/my-notes

favicon_ico:"/assets/images/favicon.ico"

nav_enabled: true

heading_anchors: true